import { Instrument_Sans } from "next/font/google";
const instrument = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

import "@/app/_styles/globals.css";
import { LinkProvider } from "./_context/LinkShareContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Metadata can also be placed here */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${instrument.className}`}>
        <LinkProvider>{children}</LinkProvider>
      </body>
    </html>
  );
}
